[package]
name = "tasky-task-manager"
version = "0.1.0"
edition = "2024"

[dependencies]

axum = { version = "0.8", features = ["macros"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
hyper = "1.6"
tokio ={ version = "1.4", features = ["full"]} 
